basePath: /v1
definitions:
  handler.allAtmsResponce:
    type: object
  handler.allOfficesResponce:
    type: object
  handler.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: The problem of finding an optimal branch of VTB Bank
  title: VTB MoreTech 5.0
  version: "1.0"
paths:
  /api/atms:
    get:
      consumes:
      - application/json
      description: Show all atms
      operationId: allAtms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.allAtmsResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: all atms
      tags:
      - atm
  /api/offices:
    get:
      consumes:
      - application/json
      description: Show all offices
      operationId: allOffices
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.allOfficesResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: all offices
      tags:
      - office
swagger: "2.0"
